### ISSUE TITLE
Incompatible Version on MacBook Air

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [pbatard/EfiFs#13]
I would like to use the drivers on my Mac but unfortunately they don't load.

I can boot up UEFT Shell v1 (v2 gives me a black screen) using Refind, then call `load f2fs_x64.efi` but it tell me the version is incompatible.

Could there be a way to make them compatible with Macs?

**Comment by pbatard** [comment]
> Could there be a way to make them compatible with Macs?

Maybe.

My only issue here is that I don't have access to a Mac displaying the issue, and, furthermore, even if I had access to one, because EfiFs is currently a lower priority project, I don't think I would be able to invest the time required to investigate and possibly fix the issue.

So, I'm afraid that I will have to rely on **someone else** with a Mac, and with the relevant development skills, to look into that problem and propose a fix.

I wish I could tell you otherwise, but that's unfortunately the reality of the current situation as, while I am aware of the issue, I currently have no insight whatsoever as to why this might be happening (though my suspicion is that Apple, who are known for that kind of practice, chose to deviate from the UEFI specifications and chose **not** to implement some of the UEFI APIs we require).

Possibly also, the reason might be the same as why you are getting a black screen when trying to run Shell v2 and not with Shell v1. I hope you can understand that adding workarounds to make the EfiFs compatible with older more limited versions of UEFI, as it'd be a bit like someone asking if a Windows 7 and later application, that doesn't run on Windows XP because it relies on the newer Windows APIs, could be retrofitted to work on Windows XP. Usually, this takes a lot of work, and the benefits are very small, since the vast majority of people wouldn't use the older platform, and, as time goes by, less and less people are expected to.

As I believe I have answered your question, I will close this issue.
