### ISSUE TITLE
pls help implementing zfs-drivers no grub

### ISSUE THREAD

**Issue by Advantaged** [pbatard/EfiFs#35]
Hi,
do you know someone can help us implementing zfs-drivers in refind?

Note: We don't intend to use grub or systemd but arch-linux and derivate.

**Comment by pbatard** [comment]
I don't think you quite understand how UEFI drivers work (or how refind or GRUB work)

UEFI, which is what rEFInd uses, doesn't depend on anything, and it doesn't matter one bit if a UEFI driver was derived from the GRUB or something else. It's still a UEFI driver designed to work at the UEFI level, which rEFInd or any other UEFI bootloader can use.

So the ZFS driver, even if derived from the GRUB source code, __DOES NOT REQUIRE GRUB IN LINUX__ or systemd, or whatever else. In fact it is used long before GRUB or systemd have a chance to initialize, because it is part of the UEFI subsystem, that comes long before the Linux kernel is even loaded.

Therefore, your question makes no sense, and nobody will help you implement a ZFS driver, be it derived from GRUB source code or not, because it's __NOT__ because something is derived from a specific codebase, that it requires the software from that codebase to run (in the same manner as, it's not because the MacOS kernel is derived from BSD that Mac users have to first load FreeBSD or OpenBSD on their machine, before they can launch MacOS).

**Comment by Advantaged** [comment]
I'm not a coder and have no clue about all these things,

anyway, thank you for explaining me at least the basics of the topic.

I come to you regarding this topic because rEFInd-developer indicate at end this [thread](https://sourceforge.net/p/refind/discussion/general/thread/4f3e274d/?limit=25) you as the provider of additional [drivers](https://efi.akeo.ie/downloads/efifs-1.8/x64/) but don't explain how to implement it/them.

Honestly spoken, I would prefer to use all drivers from one reliable source that are also up to date ("yours").
I read also that to much drivers inside rEFInd making it slower.
Install `refind --all-drivers` don't contain zfs-driver.

I haven't refind installed now but in the past, in the `refind-master/filesystems` are interesting files that tell me "it's not just a question to copy any driver somewhere" but much more and I have no clue how to do it.

Can you give me some indications?
