### ISSUE TITLE
Driver does not load correctly when added to EFI driver list

### ISSUE THREAD

**Issue by niansa** [pbatard/EfiFs#45]
On 2 different devices I have tried adding the ext2 driver to the driver list (`bcfg driver add` ...) and indeed it gets loaded at startup (verified using `drivers` command). However, no ext2 partitions are detected.

**Comment by pbatard** [comment]
In case your `ext` file system is using newer features than what GRUB supported by the time of the 1.9 release, I suggest you try the newly released 1.10 version of the ext2 driver.

Otherwise, I'm afraid I'm not seeing any issue during QEMU testing, so the issue must have to do with your environment, or the limitations of the GRUB ext driver (which is __not__ something I am going to address as this will need to be fixed in GRUB upstream):

![Image1](https://github.com/pbatard/EfiFs/assets/1206968/75980f6c-b925-407f-a088-dcb09a4ca0a6)
